package com.onlineShop.example.commonUtilMethods;

public enum SearchOperation {
	GREATER_THAN, LESS_THAN, GREATER_THAN_EQUAL, LESS_THAN_EQUAL, NOT_EQUAL, EQUAL, MATCH, MATCH_START, MATCH_END, IN,
	NOT_IN,COMPOSITE,NESTED_COMPOSITE,DATE_LESS_THAN,DATE_GREATER_THAN, DATE_BETWEEN, DATE_LESS_THAN_OR_EQAUL,
	DATE_GREATER_THAN_OR_EQAUL, VISIBILITY_TRUE, VISIBILITY_FALSE, IS_NULL, IS_NOT_NULL, IN_OR_NULL, IN_OR_NULL_COMPOSITE, 
	IN_OR_NULL_NESTED_COMPOSITE ,NOT_EQUAL_COMPOSITE,IS_NOT_NULL_COMPOSITE,IN_COMPOSITE,MATCH_COMPOSITE

}
