ALTER SESSION SET CURRENT_SCHEMA="SHOP_ADMIN";
GRANT SELECT,INSERT,UPDATE,DELETE ON SHOP_ADMIN.TB_OS_DB_ERR  TO SHOP_APP;
GRANT SELECT,INSERT,UPDATE,DELETE ON shop_ADMIN.TB_os_ENCRYPTN_B  TO shop_APP;
GRANT SELECT,INSERT,UPDATE,DELETE ON RPS_ADMIN.TB_OS_USR_B  TO SHOP_APP;
