CREATE TABLE TB_OS_DB_CUSTOMERS
(
	ID					NUMBER(38,0) NOT NUL,
	USERNAME			VARCHAR2(100) NOT NULL,
	PASSWORD			VARCHAR2(100),
	FIRST_NAME			VARCHAR2(100),
	LAST_NAME			VARCHAR2(100),
	MOBILE_NO			VARCHAR2(50) NOT NULL,
	EMAIL				VARCHAR2(100) NOT NULL,
	PROFIL_PIC			BLOB(200),
	CRT_TS          	TIMESTAMP(6),
	CRT_BY				VARCHAR2(100),
	UPD_TS				TIMESTAMP(6),
	UPD_BY				VARCHAR2(100)
);

ALTER TABLE TB_OS_DB_CUSTOMERS ADD CONSTRAINTS OS_DB_CUSTOMERS_PK PRIARY KEY(ID);
ALTER TABLE TB_OS_DB_CUSTOMERS ADD CONSTRAINTS OS_DB_CUSTOMERS_UNIQ UNIQUE(USERNAME);
ALTER TABLE TB_OS_DB_CUSTOMERS ADD CONSTRAINTS OS_DB_CUSTOMERS_UNIQ UNIQUE(MOBILE_NO);
ALTER TABLE TB_OS_DB_CUSTOMERS ADD CONSTRAINTS OS_DB_CUSTOMERS_UNIQ UNIQUE(EMAIL);


CREATE TABLE TB_OS_DB_ADDRESS
(
	ID				NUMBER(38,0) NOT NULL,
	CUSTOMER_ID		NUMBER(38,90 NOT NULL, 
	ADDRESS_LINE1	VARCHAR2(300),
	ADDRESS_LINE2	VARCHAR2(300),
	CIY				VARCHAR2(50),
	POSTAL_CODE		VARCHAR2(50) NOT NULL,
	COUNTRY			VARCHAR(59) NOT NULL,
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(100),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(100)

);
ALTER TABLE TB_OS_DB_ADDRESS ADD CONSTRAINTS OS_DB_ADDRESS_PK PRIMARY KEY(ID);


CREATE TABLE TB_OS_DB_PAYMENTS
(
	ID				NUMBER(38,0) NOT NULL,
	CUSTOMER_ID     NUMBER(38,0) NOT NULL,
	PAYMENT_TYPE	VARCHAR2(100),
	PROVIDER		VARCHAR2(100),
	ACCOUNT_NO		VARCHAR2(200) NOT NULL,
	EXPIRY			TIMESTAMP(6),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(100)
	
);
ALTER TABLE TB_OS_DB_PAYMENTS ADD CONSTRAINTS OS_DB_CUSTOMERS_PK PRIMARY KEY(ID);


CREATE TABLE TB_OS_DB_PRODUCTS
(
	ID				NUMBER(38,0) NOT NULL,
	NAME			VARCHAR2(100),
	DESCR			VARCHAR2(2000),
	PRICE			DECIMAL(38,2),
	CATAGORY_ID	 	NUMBER(38,0),
	INVENTORY_ID 	NUMBER(38,0),
	DISCOUNT_ID		NUMBER(38,0),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(38,0),
	UPD_BY			VARCHAR2(50),
	DLT_TS			TIMESTAMP(6),
	DLT_BY			VARCHAR2(50)
	
);
ALTER TABLE TB_OS_DB_PRODUCTS ADD CONSTRAINTS OS_DB_CUSTOMERS_PK PRIMARY KEY(ID);


CREATE TABLE TB_OS_DB_CATAGORY
(
	ID			NUMBER(38,0) NOT NULL,
	NAME		VARCHAR2(50),
	DESCR		VARCHAR2(200),
	CRT_TS		TIMESTAMP(6),
	CRT_BY		VARCHAR2(50),
	UPD_TS		TIMESTAMP(6),
	UPD_BY		VARCHAR2(50),
	DLT_TS		TIMESTAMP(6),
	DLT_BY		VARCHAR2(50)
)

ALTER TABLE TB_OS_DB_CATAGORY ADD CONSTRAINTS OS_DB_CATAGORY_PK PRIMARY KEY(ID);



CREATE TABLE TB_OS_DB_INVENTORY
(
	ID			NUMBER(38,0) NOT NULL,
	QUANTITY	NUMBER(38,0),
	CRT_TS		TIMESTAMP(6),
	CRT_BY		VARCHAR2(50),
	UPD_TS		TIMESTAMP(6),
	UPD_BY		VARCHAR2(50),
	DLT_TS		TIMESTAMP(6),
	DLT_BY		VARCHAR2(50)
)
ALTER TABLE TB_OS_DB_INVENTORY ADD CONSTRAINTS OS_DB_INVENTORY_PK PRIMARY KEY(ID);



CREATE TABLE TB_OS_DB_DISCOUNT
(
	ID			NUMBER(38,0) NOT NULL,
	NAME		VARCHAR2(100),
	DESCR		VARCHAR2(2000),
	DISCOUNT_PERSENT	DECIMAL(38,2),
	ACTIV				VARCHAR2(2),
	CRT_TS				TIMESTAMP(6),
	CRT_BY				VARCHAR2(50),
	UPD_TS				TIMESTAMP(6),
	UPD_BY				VARCHAR2(50),
	DLT_TS				TIMESTAMP(6),
	DLT_BY				VARCHAR2(50)
	
);

ALTER TABLE TB_OS_DB_DISCOUNT ADD CONSTRAINTS TB_OS_DB_DISCOUNT_PK PRIMARY KEY(ID);

CREATE TABLE TB_OS_DB_CARDITEM
(
	ID				NUMBER(38,0) NOT NULL,
	SESSION_ID		NUMBER(38,0) NOT NULL,
	PRODUCT_ID		NUMBER(38,0) NOT NULL,
	QUANTITY        NUMBER(38,0),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(50)
);
ALTER TABLE TB_OS_DB_CARDITEM ADD CONSTRAINTS OS_DB_CARDITEM_PK PRIMARY KEY(ID);

CREATE TABLE TB_OS_DB_SHOPPINGSESSION
(
	ID				NUMBER(38,0) NOT NULL,
	CUSTOMER_ID		NUMBER(38,0) NOT NULL,
	TOTAL_AMT			NUMBER(38,0),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(50)
);

ALTER TABLE TB_OS_DB_SHOPPINGSESSION ADD CONSTRAINTS OS_DB_CARDITEM_PK PRIMARY KEY(ID);





CREATE TABLE TB_OS_DB_ORDERITEMS
(
	ID				NUMBER(38,0) NOT NULL,
	ORDER_ID		NUMBER(38,0) NOT NULL,
	PRODUCT_ID		NUMBER(38,00 NOT NULL,
	QUANTITY		NUMBER(38,0),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(38,0),
	UPD_BY			VARCHAR2(50)
);

ALTER TABLE TB_OS_DB_ORDERITEMS ADD CONSTRAINTS OS_DB_CARDITEM_PK PRIMARY KEY(ID);


CREATE TABLE TB_OS_DB_ORDERDETAILS
(
	ID				NUMBER(38,0) NOT NULL,
	CUSTOMER_ID		NUMBER38,0),
	TOTAL			NUMBER(38,2),
	PAYMENT_ID		NUMBER(38,0),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(50)
);

ALTER TABLE TB_OS_DB_ORDERDETAILS ADD CONSTRAINTS OS_DB_CARDITEM_PK PRIMARY KEY(ID);


CREATE TABLE TB_OS_DB_PAYMENTSDETAILS
(
	ID				NUMBER(38,0) NOT NULL,
	ORDER_ID		NUMBER(38,0) NOT NULL,
	ACCOUNT_NO		VARCHAR2(50),
	PROVIDER		VARCHAR2(50),
	STATUS			VARCHAR2(30),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(50)
);
ALTER TABLE TB_OS_DB_PAYMENTSDETAILS ADD CONSTRAINTS OS_DB_CARDITEM_PK PRIMARY KEY(ID);