CREATE SEQUENCE SEQ_OS_DB_ERR START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_ENCRYPTN START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_USR START WITH 1 INCREMENT BY 1 NOMAXVALUE ;



-- NEW SEQUENCE

CREATE SEQUENCE SEQ_OS_COUNTRY START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_STATE START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_CITY START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_DELE START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_COLONY START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_POSTAL START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_ADDRESS START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_CUSTOMERS START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_PAYMENTS START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_PRODUCTS START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_CATAGORY START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_INVENTORY START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_DISCOUNT START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_CARDITEM START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_SHOPPINGSESSION START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_ORDERITEMS START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_ORDERDETAILS START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_PAYMENTSDETAILS START WITH 1 INCREMENT BY 1 NOMAXVALUE ;