CREATE SEQUENCE SEQ_OS_DB_ERR START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_ENCRYPTN START WITH 1 INCREMENT BY 1 NOMAXVALUE ;
CREATE SEQUENCE SEQ_OS_USR START WITH 1 INCREMENT BY 1 NOMAXVALUE ;