CREATE TABLE TB_OS_DB_ERR
(
ID					NUMBER(30,0) NOT NULL,
REF_CD				VARCHAR2(100),
ERR_CD				VARCHAR2(100),
ERR_MSG				VARCHAR2(4000),
REF_NM				VARCHAR2(100),
CRT_BY				VARCHAR2(50) DEFAULT USER,
CRT_TS				TIMESTAMP(6) DEFAULT SYSTIMESTAMP

);
ALTER TABLE TB_OS_DB_ERR ADD CONSTRAINTS OS_DB_ERR_PK PRIMARY KEY(ID);

CREATE TABLE TB_OS_USER
(
ID					NUMBER(38,0) NOT NULL,
REF_ID				VARCHAR2(50) NOT NULL,
PSWD				VARCHAR2(200) NOT NULL,
FULL_NM				NVARCHAR2(100) NOT NULL,
DSPL_NM				NVARCHAR2(30) NOT NULL,
EMAIL				VARCHAR2(2000),
CNTCT_INFO			NVARCHAR2(50),
CNTCT_NUMBER		VARCHAR2(50),
DSGN				VARCHAR2(50),
LOCATION			NVARCHAR2(50),
FLD_LGN_CNT			NUMBER(15,0) DEFAULT 0,
LST_LGN_TS			TIMESTAMP(6),
EXPR_TS				TIMESTAMP(6),
PSWD_CRT_BY			VARCHAR2(50),
USER_STATE			VARCHAR2(50) NOT NULL,
SESSION_ID			VARCHAR2(50),
LDAP_AUTH			VARCHAR2(50) DEFAULT 'N',
--ENC_KEY_ID			NUMBER(38,0),
SKIP_INACTVN		VARCHAR2(1) DEFAULT 'N',
CRT_TS				TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
CRT_BY				VARCHAR2(50) DEFAULT USER,
UPD_TS				TIMESTAMP(6),
UPD_BY				VARCHAR2(50),
DLT_TS				TIMESTAMP(6),
DLT_BY				VARCHAR2(50),
);



ALTER TABLE TB_OS_USER ADD CONSTRAINTS OS_USER_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_USER ADD CONSTRAINTS OS_USER_UNIQ UNIQUE(REF_ID);
ALTER TABLE TB_OS_USER ADD CONSTRAINTS OS_USER_EMAIL_UNIQ UNIQUE(EMAIL);
--ALTER TABLE TB_OS_USER ADD CONSTRAINTS OS_USER_OS_ENC_KEY_FK FOREIGN KEY (ENC_KEY_ID) REFERENCES TB_OS_ENCRYPTN(ID);


CREATE TABLE TB_OS_ENCRYPTN
(
ID					NUMBER(38,0) NOT NULL,
KEY					VARCHAR2(4000),
SALT				VARCHAR2(4000),
IS_ACTV				VARCHAR2(2) NOT NULL,
KEK_JKS_PATH		VARCHAR2(2000),
KEK_JKS_PSWD		VARCHAR2(200),
CUSTODIAN_1_KEY		VARCHAR2(4000),
CUSTODIAN_1_SALT	VARCHAR2(4000),
CUSTODIAN_2_KEY		VARCHAR2(4000),
CUSTODIAN_2_SALT	VARCHAR2(4000),
CRT_BY				VARCHAR2(50) DEFAULT USER,
CRT_TS				TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
UPS_BY				VARCHAR2(50),
UPD_TS				TIMESTAMP(6),
);
ALTER TABLE TB_OS_ENCRYPTN ADD CONSTRAINTS OS_ENCRYPTN_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_ENCRYPTN ADD CONSTRAINTS OS_ENCRYPTN_UNIQ UNIQUE(KEY);
















