CREATE TABLE TB_OS_DB_ERR
(
ID					NUMBER(30,0) NOT NULL,
REF_CD				VARCHAR2(100),
ERR_CD				VARCHAR2(100),
ERR_MSG				VARCHAR2(4000),
REF_NM				VARCHAR2(100),
CRT_BY				VARCHAR2(50) DEFAULT USER,
CRT_TS				TIMESTAMP(6) DEFAULT SYSTIMESTAMP

);
ALTER TABLE TB_OS_DB_ERR ADD CONSTRAINTS OS_DB_ERR_PK PRIMARY KEY(ID);

CREATE TABLE TB_OS_USER
(
ID					NUMBER(38,0) NOT NULL,
REF_ID				VARCHAR2(50) NOT NULL,
PSWD				VARCHAR2(200) NOT NULL,
FULL_NM				NVARCHAR2(100) NOT NULL,
DSPL_NM				NVARCHAR2(30) NOT NULL,
EMAIL				VARCHAR2(2000),
CNTCT_INFO			NVARCHAR2(50),
CNTCT_NUMBER		VARCHAR2(50),
DSGN				VARCHAR2(50),
LOCATION			NVARCHAR2(50),
FLD_LGN_CNT			NUMBER(15,0) DEFAULT 0,
LST_LGN_TS			TIMESTAMP(6),
EXPR_TS				TIMESTAMP(6),
PSWD_CRT_BY			VARCHAR2(50),
USER_STATE			VARCHAR2(50) NOT NULL,
SESSION_ID			VARCHAR2(50),
LDAP_AUTH			VARCHAR2(50) DEFAULT 'N',
--ENC_KEY_ID			NUMBER(38,0),
SKIP_INACTVN		VARCHAR2(1) DEFAULT 'N',
CRT_TS				TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
CRT_BY				VARCHAR2(50) DEFAULT USER,
UPD_TS				TIMESTAMP(6),
UPD_BY				VARCHAR2(50),
DLT_TS				TIMESTAMP(6),
DLT_BY				VARCHAR2(50)
);



ALTER TABLE TB_OS_USER ADD CONSTRAINTS OS_USER_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_USER ADD CONSTRAINTS OS_USER_UNIQ UNIQUE(REF_ID);
ALTER TABLE TB_OS_USER ADD CONSTRAINTS OS_USER_EMAIL_UNIQ UNIQUE(EMAIL);
--ALTER TABLE TB_OS_USER ADD CONSTRAINTS OS_USER_OS_ENC_KEY_FK FOREIGN KEY (ENC_KEY_ID) REFERENCES TB_OS_ENCRYPTN(ID);


CREATE TABLE TB_OS_ENCRYPTN
(
ID					NUMBER(38,0) NOT NULL,
KEY					VARCHAR2(4000),
SALT				VARCHAR2(4000),
IS_ACTV				VARCHAR2(2) NOT NULL,
KEK_JKS_PATH		VARCHAR2(2000),
KEK_JKS_PSWD		VARCHAR2(200),
CUSTODIAN_1_KEY		VARCHAR2(4000),
CUSTODIAN_1_SALT	VARCHAR2(4000),
CUSTODIAN_2_KEY		VARCHAR2(4000),
CUSTODIAN_2_SALT	VARCHAR2(4000),
CRT_BY				VARCHAR2(50) DEFAULT USER,
CRT_TS				TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
UPS_BY				VARCHAR2(50),
UPD_TS				TIMESTAMP(6)
);
ALTER TABLE TB_OS_ENCRYPTN ADD CONSTRAINTS OS_ENCRYPTN_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_ENCRYPTN ADD CONSTRAINTS OS_ENCRYPTN_UNIQ UNIQUE(KEY);






-- new buisness tables for store data ;ike customers, products, etc.





-- ADDRESS TABLES FOR STORE DATABASE
CREATE TABLE TB_OS_COUNTRY		
(
	ID				NUMBER(38) NOT NULL ,
	NM   			VARCHAR2(50) NOT NULL,
	NUM_CD			NUMBER(5) NOT NULL,--91
	ALPHA_CD_2		VARCHAR2(2) NOT NULL,--IN
	ALPHA_CD_3		VARCHAR2(3) NOT NULL,--IND
	UPD_BY			VARCHAR2(50) DEFAULT USER NOT NULL,		
	UPD_TS			TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL
); 

ALTER TABLE TB_OS_COUNTRY ADD CONSTRAINT OS_COUNTRY_PK PRIMARY KEY(ID); 



--dml script
CREATE TABLE TB_OS_STATE			
(
	ID				NUMBER(38,0) NOT NULL , 
	COUNTRY_ID 		NUMBER(38) NOT NULL ,
	CD				VARCHAR2(30),
	NM				VARCHAR2(100),
	UPD_BY			VARCHAR2(50) DEFAULT USER NOT NULL,		
	UPD_TS			TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE TB_OS_STATE ADD CONSTRAINT OS_STATE_PK PRIMARY KEY(ID); 
ALTER TABLE TB_OS_STATE ADD CONSTRAINT OS_STATE_OS_COUNTRY_FK FOREIGN KEY (COUNTRY_ID) REFERENCES TB_OS_COUNTRY (ID); 

--dml script
CREATE TABLE TB_OS_CITY			
(
	ID				NUMBER(38,0) NOT NULL , 
	STATE_ID		NUMBER(38,0) NOT NULL ,
	CD          	VARCHAR2(30),
	NM				VARCHAR2(100),
	UPD_BY			VARCHAR2(50) DEFAULT USER NOT NULL,		
	UPD_TS			TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE TB_OS_CITY ADD CONSTRAINT OS_CITY_PK PRIMARY KEY(ID); 
ALTER TABLE TB_OS_CITY ADD CONSTRAINT OS_CITY_OS_STATE_FK FOREIGN KEY (STATE_ID) REFERENCES TB_OS_STATE (ID);

--dml script
CREATE TABLE TB_OS_DELE				
(
	ID				NUMBER(38) NOT NULL , 
	CITY_ID			NUMBER(38) NOT NULL ,
	CD				VARCHAR2(30),
	NM				VARCHAR2(100),
	UPD_BY			VARCHAR2(50) DEFAULT USER NOT NULL,		
	UPD_TS			TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE TB_OS_DELE ADD CONSTRAINT OS_DELE_PK PRIMARY KEY(ID); 
ALTER TABLE TB_OS_DELE ADD CONSTRAINT OS_DELE_OS_CITY_FK FOREIGN KEY (CITY_ID) REFERENCES TB_OS_CITY (ID);

--dml script
CREATE TABLE TB_OS_COLONY			
(
	ID				NUMBER(38,0) NOT NULL , 
	DELEG_ID		NUMBER(38,0) NOT NULL , 	
	CD				VARCHAR2(30),
	NM				VARCHAR2(100),
	UPD_BY			VARCHAR2(50) DEFAULT USER NOT NULL,		
	UPD_TS			TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE TB_OS_COLONY ADD CONSTRAINT OS__COLONY_PK PRIMARY KEY(ID); 
ALTER TABLE TB_OS_COLONY ADD CONSTRAINT OS_COLONY_OS_DELE_FK FOREIGN KEY (DELEG_ID) REFERENCES TB_OS_DELE (ID);

--dml script
CREATE TABLE TB_OS_POSTAL			
(
	ID			NUMBER(38) NOT NULL , 
	COLONY_ID	NUMBER(38) NOT NULL , 		
	CD			VARCHAR2(30) NOT NULL,	
	NM			VARCHAR2(100),
	UPD_BY		VARCHAR2(50) DEFAULT USER NOT NULL,		
	UPD_TS		TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE TB_OS_POSTAL ADD CONSTRAINT OS_POSTAL_PK PRIMARY KEY(ID); 
ALTER TABLE TB_OS_POSTAL ADD CONSTRAINT OS_POSTAL_OS_COLO_FK FOREIGN KEY (COLONY_ID) REFERENCES TB_OS_COLONY (ID); 

CREATE TABLE TB_OS_ADRS
(
	ID					NUMBER(38,0) NOT NULL ,
	HOUSE_NO			VARCHAR2(10),
	STREET_NO			VARCHAR2(100),
	COLO_ID			    NUMBER(38,0) NOT NULL,		--FK
	DELEG_ID		    NUMBER(38,0)NOT NULL,		--FK
	CITY_ID			    NUMBER(38,0)NOT NULL,		--FK
	STATE_ID			NUMBER(38,0)NOT NULL,		--FK
	COUNTRY_ID 			NUMBER(38,0) NOT NULL , 		--FK
	POSTAL_ID			NUMBER(33,0) NOT NULL,           --FK
	ADDR_TYPE			VARCHAR2(20),	--permanent/residencial/office etc
	--ADDR_STS 			VARCHAR2(30),-- NOT NULL,	--(active,inactive)
	CRT_TS			    TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL,			
	CRT_BY              VARCHAR2(50),
	UPD_TS			    TIMESTAMP (6) ,
	UPD_BY              VARCHAR2(50)

);
ALTER TABLE TB_OS_ADRS ADD CONSTRAINT OS_ADRS_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_ADRS ADD CONSTRAINT OS_ADRS_OS_COLONY_FK FOREIGN KEY (COLO_ID) REFERENCES TB_OS_COLONY(ID);
ALTER TABLE TB_OS_ADRS ADD CONSTRAINT OS_ADRS_OS_DELE_FK FOREIGN KEY(DELEG_ID) REFERENCES TB_OS_DELE(ID);
ALTER TABLE TB_OS_ADRS ADD CONSTRAINT OS_ADRS_OS_CITY_FK FOREIGN KEY(CITY_ID) REFERENCES TB_OS_CITY(ID);
ALTER TABLE TB_OS_ADRS ADD CONSTRAINT OS_ADRS_OS_STATE_FK FOREIGN KEY(STATE_ID) REFERENCES TB_OS_STATE(ID);
ALTER TABLE TB_OS_ADRS ADD CONSTRAINT OS_ADRS_OS_COUNTRY_FK FOREIGN KEY(COUNTRY_ID) REFERENCES TB_OS_COUNTRY(ID);
ALTER TABLE TB_OS_ADRS ADD CONSTRAINT OS_ADRS_OS_POSTAL_FK FOREIGN KEY(POSTAL_ID) REFERENCES TB_OS_POSTAL(ID);


--ADD CUSTOMERS TABLES FOR STORE CUSTOMERS DETAILS
CREATE TABLE TB_OS_PAYMENTS
(
	ID				NUMBER(38,0) NOT NULL,
	CUSTOMER_ID     NUMBER(38,0) NOT NULL,
	PAYMENT_TYPE	VARCHAR2(100),
	PROVIDER		VARCHAR2(100),
	ACCOUNT_NO		VARCHAR2(200) NOT NULL,
	EXPIRY			TIMESTAMP(6),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(100)
	
);
ALTER TABLE TB_OS_PAYMENTS ADD CONSTRAINT OS_PAYMENTS_PK PRIMARY KEY(ID);


CREATE TABLE TB_OS_CUSTMR
(
ID					NUMBER(38,0) NOT NULL,
REF_ID				VARCHAR2(50) NOT NULL, -- USERNAME LIKE SRK1, sharik123 etc.
PSWD				VARCHAR2(200) NOT NULL, -- in hash format
FULL_NM				NVARCHAR2(100) NOT NULL,
DSPL_NM				NVARCHAR2(30) NOT NULL,
EMAIL				VARCHAR2(2000),
CNTCT_INFO			NVARCHAR2(50),
CNTCT_NUMBER		VARCHAR2(50),
DSGN				VARCHAR2(50),
LOCATION			NVARCHAR2(50),
FLD_LGN_CNT			NUMBER(15,0) DEFAULT 0,
LST_LGN_TS			TIMESTAMP(6),
EXPR_TS				TIMESTAMP(6),
PSWD_CRT_BY			VARCHAR2(50),
ADDRESS_ID			NUMBER(38,0),
PAYMENTS_ID			NUMBER(38,0),
USER_STATE			VARCHAR2(50) ,--NOT NULL,
SESSION_ID			VARCHAR2(50),
LDAP_AUTH			VARCHAR2(50) DEFAULT 'N',
--ENC_KEY_ID			NUMBER(38,0),
SKIP_INACTVN		VARCHAR2(1) DEFAULT 'N',
CRT_TS				TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
CRT_BY				VARCHAR2(50) DEFAULT USER,
UPD_TS				TIMESTAMP(6),
UPD_BY				VARCHAR2(50),
DLT_TS				TIMESTAMP(6),
DLT_BY				VARCHAR2(50)
);

ALTER TABLE TB_OS_CUSTMR ADD CONSTRAINT OS_CUSTMR_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_CUSTMR ADD CONSTRAINT OS_CUSTMR_UNIQ UNIQUE(REF_ID);
ALTER TABLE TB_OS_CUSTMR ADD CONSTRAINT OS_CUSTMR_CONT_UNIQ UNIQUE(CNTCT_NUMBER);
ALTER TABLE TB_OS_CUSTMR ADD CONSTRAINT OS_CUSTMR_EMAIL_UNIQ UNIQUE(EMAIL);
ALTER TABLE TB_OS_CUSTMR ADD CONSTRAINT OS_CUSTMR_OS_ADRS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES TB_OS_ADRS(ID);
ALTER TABLE TB_OS_CUSTMR ADD CONSTRAINT OS_CUSTMR_OS_PAYMENTS_FK FOREIGN KEY (PAYMENTS_ID) REFERENCES TB_OS_PAYMENTS(ID);


--PRODUCT MANAGEMENTS


CREATE TABLE TB_OS_CATAGORY
(
	ID			NUMBER(38,0) NOT NULL,
	NAME		VARCHAR2(50),
	DESCR		VARCHAR2(200),
	CRT_TS		TIMESTAMP(6),
	CRT_BY		VARCHAR2(50),
	UPD_TS		TIMESTAMP(6),
	UPD_BY		VARCHAR2(50),
	DLT_TS		TIMESTAMP(6),
	DLT_BY		VARCHAR2(50)
);

ALTER TABLE TB_OS_CATAGORY ADD CONSTRAINT OS_CATAGORY_PK PRIMARY KEY(ID);



CREATE TABLE TB_OS_INVENTORY
(
	ID			NUMBER(38,0) NOT NULL,
	QUANTITY	NUMBER(38,0),
	CRT_TS		TIMESTAMP(6),
	CRT_BY		VARCHAR2(50),
	UPD_TS		TIMESTAMP(6),
	UPD_BY		VARCHAR2(50),
	DLT_TS		TIMESTAMP(6),
	DLT_BY		VARCHAR2(50)
);
ALTER TABLE TB_OS_INVENTORY ADD CONSTRAINT OS_INVENTORY_PK PRIMARY KEY(ID);



CREATE TABLE TB_OS_DISCOUNT
(
	ID					NUMBER(38,0) NOT NULL,
	NAME				VARCHAR2(100),
	DESCR				VARCHAR2(2000),
	DISCOUNT_PERSENT	DECIMAL(38,2),
	ACTIV				VARCHAR2(2),
	CRT_TS				TIMESTAMP(6),
	CRT_BY				VARCHAR2(50),
	UPD_TS				TIMESTAMP(6),
	UPD_BY				VARCHAR2(50),
	DLT_TS				TIMESTAMP(6),
	DLT_BY				VARCHAR2(50)
	
);

ALTER TABLE TB_OS_DISCOUNT ADD CONSTRAINT OS_DISCOUNT_PK PRIMARY KEY(ID);


CREATE TABLE TB_OS_PRODUCTS
(
	ID				NUMBER(38,0) NOT NULL,
	NAME			VARCHAR2(100),
	DESCR			VARCHAR2(2000),
	PRICE			DECIMAL(38,2),
	CATAGORY_ID	 	NUMBER(38,0),
	INVENTORY_ID 	NUMBER(38,0),
	DISCOUNT_ID		NUMBER(38,0),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(50),
	DLT_TS			TIMESTAMP(6),
	DLT_BY			VARCHAR2(50)
	
);
ALTER TABLE TB_OS_PRODUCTS ADD CONSTRAINT OS_PRODUCTS_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_PRODUCTS ADD CONSTRAINT OS_PRODUCTS_OS_CATAGORY_FK FOREIGN KEY(CATAGORY_ID) REFERENCES TB_OS_CATAGORY(ID);
ALTER TABLE TB_OS_PRODUCTS ADD CONSTRAINT OS_PRODUCTS_OS_INVENTORY_FK FOREIGN KEY(INVENTORY_ID) REFERENCES TB_OS_INVENTORY(ID);
ALTER TABLE TB_OS_PRODUCTS ADD CONSTRAINT OS__PRODUCTS_OS_DISCOUNT_FK FOREIGN KEY(DISCOUNT_ID) REFERENCES TB_OS_DISCOUNT(ID);


--SHOPPING SESSION

CREATE TABLE TB_OS_SHOPSESON
(
	ID				NUMBER(38,0) NOT NULL,
	CUSTOMER_ID		NUMBER(38,0) NOT NULL,
	TOTAL_AMT			NUMBER(38,0),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(50)
);

ALTER TABLE TB_OS_SHOPSESON ADD CONSTRAINT OS_SHOPSESON_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_SHOPSESON ADD CONSTRAINT OS_SHOPSESON_OS_CUSTMR_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES TB_OS_CUSTMR(ID);



CREATE TABLE TB_OS_CARDITEM
(
	ID				NUMBER(38,0) NOT NULL,
	SESSION_ID		NUMBER(38,0) NOT NULL,
	PRODUCT_ID		NUMBER(38,0) NOT NULL,
	QUANTITY        NUMBER(38,0),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(50)
);
ALTER TABLE TB_OS_CARDITEM ADD CONSTRAINT OS_CARDITEM_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_CARDITEM ADD CONSTRAINT OS_CARDITEM_OS_SHOPSESON_FK FOREIGN KEY(SESSION_ID) REFERENCES TB_OS_SHOPSESON(ID);
ALTER TABLE TB_OS_CARDITEM ADD CONSTRAINT OS_CARDITEM_OS_PRODUCTS_FK FOREIGN KEY(PRODUCT_ID) REFERENCES TB_OS_PRODUCTS(ID);



CREATE TABLE TB_OS_ORDDETLS
(
	ID				NUMBER(38,0) NOT NULL,
	CUSTOMER_ID		NUMBER(38,0),
	TOTAL			NUMBER(38,2),
	PAYMENT_ID		NUMBER(38,0),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(50)
);

ALTER TABLE TB_OS_ORDDETLS ADD CONSTRAINT OS_ORDDETLS_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_ORDDETLS ADD CONSTRAINT OS_ORDDETLS_OS_CUSTMR_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES TB_OS_CUSTMR(ID);
ALTER TABLE TB_OS_ORDDETLS ADD CONSTRAINT OS_ORDDETLS_OS_PAYMENTS_FK FOREIGN KEY(PAYMENT_ID) REFERENCES TB_OS_PAYMENTS(ID);


CREATE TABLE TB_OS_ORDITEM
(
	ID				NUMBER(38,0) NOT NULL,
	ORDER_ID		NUMBER(38,0) NOT NULL,
	PRODUCT_ID		NUMBER(38,0) NOT NULL,
	QUANTITY		NUMBER(38,0),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(50)
);

ALTER TABLE TB_OS_ORDITEM ADD CONSTRAINT OS_ORDITEM_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_ORDITEM ADD CONSTRAINT OS_ORDITEM_OS_ORDDETLS_FK FOREIGN KEY(ORDER_ID) REFERENCES TB_OS_ORDDETLS(ID);
ALTER TABLE TB_OS_ORDITEM ADD CONSTRAINT OS_ORDITEM_OS_PRODUCTS_FK FOREIGN KEY(PRODUCT_ID) REFERENCES TB_OS_PRODUCTS(ID);



CREATE TABLE TB_OS_PYMTDETL
(
	ID				NUMBER(38,0) NOT NULL,
	ORDER_ID		NUMBER(38,0) NOT NULL,
	ACCOUNT_NO		VARCHAR2(50),
	PROVIDER		VARCHAR2(50),
	STATUS			VARCHAR2(30),
	CRT_TS			TIMESTAMP(6),
	CRT_BY			VARCHAR2(50),
	UPD_TS			TIMESTAMP(6),
	UPD_BY			VARCHAR2(50)
);
ALTER TABLE TB_OS_PYMTDETL ADD CONSTRAINT OS_PYMTDETL_PK PRIMARY KEY(ID);
ALTER TABLE TB_OS_PYMTDETL ADD CONSTRAINT OS_PYMTDETL_OS_ORDDETLS_FK FOREIGN KEY(ORDER_ID) REFERENCES TB_OS_ORDDETLS(ID);






